[package]
name = "ODM_"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
reqwest = { version = "0.12", features = ["stream"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
futures-util = "0.3"
sha2 = "0.10"
